apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: endpoints-reader
rules:
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "extensions" ]
    resources: [ "ingresses" ]
    verbs: [ "get","watch","list" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "list","watch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: endpoints-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: endpoints-reader
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
