apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: pubsub
      app.kubernetes.io/name: pubsub
      statefulset.kubernetes.io/pod-name: pubsub
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: pubsub
        app.kubernetes.io/name: pubsub
        statefulset.kubernetes.io/pod-name: pubsub
    spec:
      containers:
        - image: messagebird/gcloud-pubsub-emulator:latest
          name: pubsub
          ports:
            - containerPort: 8681
              protocol: TCP
          env:
            - name: PUBSUB_PROJECT1
              value: nash-iam-emulate,reception-preauth-inbound:reception-preauth-inbound-sub
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-reader
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: pubsub
    statefulset.kubernetes.io/pod-name: pubsub
  name: pubsub
spec:
  ports:
    - name: "pubsub"
      port: 8681
      protocol: TCP
      targetPort: 8681
  selector:
    app.kubernetes.io/instance: pubsub
    statefulset.kubernetes.io/pod-name: pubsub
