apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-ui
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: primary
      app.kubernetes.io/instance: pubsub-ui
      app.kubernetes.io/name: pubsub-ui
      statefulset.kubernetes.io/pod-name: pubsub-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/component: primary
        app.kubernetes.io/instance: pubsub-ui
        app.kubernetes.io/name: pubsub-ui
        statefulset.kubernetes.io/pod-name: pubsub-ui
    spec:
      containers:
        - image: ghcr.io/neoscript/pubsub-emulator-ui:latest
          name: pubsub-ui
          ports:
            - containerPort: 7200
              protocol: TCP
      restartPolicy: Always
