FROM liquibase/liquibase:latest
WORKDIR ./axon
COPY liquibase/ .
CMD \
liquibase --defaults-file=tilt-liquibase.properties --changelog-file=local-init.sql --url=jdbc:postgresql://postgresql:5432/postgres?currentSchema=public update && \
liquibase --defaults-file=tilt-liquibase.properties --changelog-file=db/db.local.changelog.yaml --url=jdbc:postgresql://postgresql:5432/eventstore?currentSchema=public update
