apiVersion: apps/v1
kind: Deployment
metadata:
  name: nash-reception-adapter
  namespace: default
  labels:
    app: nash-reception-adapter
    app.kubernetes.io/component: nash-reception-adapter
    app.kubernetes.io/instance: nash-reception-adapter
    app.kubernetes.io/name: nash-reception-adapter
spec:
  selector:
    matchLabels:
      app: nash-reception-adapter
      app.kubernetes.io/component: nash-reception-adapter
      app.kubernetes.io/instance: nash-reception-adapter
      app.kubernetes.io/name: nash-reception-adapter
  template:
    metadata:
      labels:
        app: nash-reception-adapter
        app.kubernetes.io/component: nash-reception-adapter
        app.kubernetes.io/instance: nash-reception-adapter
        app.kubernetes.io/name: nash-reception-adapter
    spec:
      containers:
        - name: nash-reception-adapter
          image: nash-reception-adapter
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: GOOGLE_CLOUD_PROJECT
              value: nash-iam-emulate
            - name: LOG_LEVEL
              value: INFO
            - name: PUBSUB_EMULATOR_HOST
              value: pubsub:8681
            - name: PUBSUB_PROJECT_ID
              value: nash-iam-emulate
            - name: SPRING_PROFILES_ACTIVE
              value: local
            - name: SPRING_CLOUD_KUBERNETES_DISCOVERY_CATALOGSERVICESWATCHDELAY
              value: '10000'
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: nash-reception-adapter
    app.kubernetes.io/instance: nash-reception-adapter
    app.kubernetes.io/name: nash-reception-adapter
  name: nash-reception-adapter
spec:
  ports:
    - name: "nash-reception-adapter"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: nash-reception-adapter
